//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMuscles", ReplyAction="*")]
        MyProject.ServiceReference1.CheckMusclesResponse CheckMuscles(MyProject.ServiceReference1.CheckMusclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMuscles", ReplyAction="*")]
        System.Threading.Tasks.Task<MyProject.ServiceReference1.CheckMusclesResponse> CheckMusclesAsync(MyProject.ServiceReference1.CheckMusclesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMusclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMuscles", Namespace="http://tempuri.org/", Order=0)]
        public MyProject.ServiceReference1.CheckMusclesRequestBody Body;
        
        public CheckMusclesRequest() {
        }
        
        public CheckMusclesRequest(MyProject.ServiceReference1.CheckMusclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMusclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public CheckMusclesRequestBody() {
        }
        
        public CheckMusclesRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMusclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMusclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyProject.ServiceReference1.CheckMusclesResponseBody Body;
        
        public CheckMusclesResponse() {
        }
        
        public CheckMusclesResponse(MyProject.ServiceReference1.CheckMusclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMusclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckMusclesResult;
        
        public CheckMusclesResponseBody() {
        }
        
        public CheckMusclesResponseBody(bool CheckMusclesResult) {
            this.CheckMusclesResult = CheckMusclesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MyProject.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MyProject.ServiceReference1.WebServiceSoap>, MyProject.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyProject.ServiceReference1.CheckMusclesResponse MyProject.ServiceReference1.WebServiceSoap.CheckMuscles(MyProject.ServiceReference1.CheckMusclesRequest request) {
            return base.Channel.CheckMuscles(request);
        }
        
        public bool CheckMuscles(string input) {
            MyProject.ServiceReference1.CheckMusclesRequest inValue = new MyProject.ServiceReference1.CheckMusclesRequest();
            inValue.Body = new MyProject.ServiceReference1.CheckMusclesRequestBody();
            inValue.Body.input = input;
            MyProject.ServiceReference1.CheckMusclesResponse retVal = ((MyProject.ServiceReference1.WebServiceSoap)(this)).CheckMuscles(inValue);
            return retVal.Body.CheckMusclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyProject.ServiceReference1.CheckMusclesResponse> MyProject.ServiceReference1.WebServiceSoap.CheckMusclesAsync(MyProject.ServiceReference1.CheckMusclesRequest request) {
            return base.Channel.CheckMusclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyProject.ServiceReference1.CheckMusclesResponse> CheckMusclesAsync(string input) {
            MyProject.ServiceReference1.CheckMusclesRequest inValue = new MyProject.ServiceReference1.CheckMusclesRequest();
            inValue.Body = new MyProject.ServiceReference1.CheckMusclesRequestBody();
            inValue.Body.input = input;
            return ((MyProject.ServiceReference1.WebServiceSoap)(this)).CheckMusclesAsync(inValue);
        }
    }
}
